### ISSUE TITLE
redux세팅 관련해서

### ISSUE THREAD

**Issue by Lee-Hyeong-Jin** [route-master/RouteMaster_FrontEnd#12]
제가 제대로 검토 못한 부분이 있어 issue 엽니다.

index.js 에서 App을 갑싸고 있는 부분은 Provider로 감싸서 store를 넘겨 주어야 합니다.
```
<Provider store={store}>
    <App />
</Provider>
```
이런식으로

꼼꼼하게 확인을 못했네요....

**Comment by JHyeon0915** [comment]
제가 보낸 풀리퀘 머지하면 이슈 닫아주세요!
