### ISSUE TITLE
Redux-tookit 사용 중 state 직접 변환에 대해서..

### ISSUE THREAD

**Issue by JHyeon0915** [route-master/RouteMaster_FrontEnd#13]
현재 카카오맵 브랜치에서 mapSlice를 만들었고 그 안에 리듀서를 추가하는 과정에서 eslint에러가 났습니다.

오류가 난 코드
```
setCenter: (state, action: PayloadAction<{ lat: number; lng: number }>) => {
      state.center = action.payload;
}
```

eslint 추천코드
```
setCenter: (state, action: PayloadAction<{ lat: number; lng: number }>) => {
      Object.assign(state, { center: action.payload });
}
```

원래는 두번째 코드가 맞는 방법인데 reduc-toolkit은 첫번째 방법으로 해도 무관한것 같더라고요
eslint를 끄는 게 나을까요? 아니면 정석대로 쓰는게 나을까요?
보기는 밑의 코드가 조금 더 마음의 안정을 부르긴 합니다..ㅋㅋㅋㅋ

**Comment by Lee-Hyeong-Jin** [comment]
eslint를 끄는게 나을것 같습니다!!

**Comment by Lee-Hyeong-Jin** [comment]
develop에 바로 커밋해도 될것 같아요!!
